public class Corredor{
    
    //DECLARE LOS ATRIBUTOS DE LA CLASE
    //Corredor SEGÚN LAS ESPECIFICACIONES
    //EN EL ENUNCIADO
    
    //A CONTINUACIÓN ADJUNTE TODOS LOS
    //MÉTODOS DE LA CLASE, ES DECIR, EL
    //MÉTODO CONSTRUCTOR, LOS GETTERS Y
    //LOS SETTERS
}